export const UI = {
  signUpButtons: document.querySelectorAll('#sign_up'),
  dropdown: {
    optionMenuLanguage: document.querySelector(".select-language"),
    optionMenu: document.querySelector(".select-menu"),
    selectBtn: document.querySelector(".select-btn"),
    options: document.querySelectorAll(".option"),
    activeOption: document.querySelector(".option--active"),
  },
  advertising: {
    container: document.querySelector('.advertising-container'),
    image: document.querySelector('.advertising-image'),
    title: document.querySelector('.adertising-title'),
    text: document.querySelector('.adertising-text'),
    link: document.querySelector('.adertising-link'),
  },
  flexElements: [
    document.querySelectorAll('.header-logo'),
    document.querySelectorAll('.main-footer'),
    document.querySelectorAll('.main-list__item'),
    document.querySelectorAll('.become-top'),
    document.querySelectorAll('.become-circle'),
    document.querySelectorAll('.authors-block__more-plus'),
    document.querySelectorAll('.opportunities-list'),
    document.querySelectorAll('.opportunities-block__check'),
    document.querySelectorAll('.tools-block'),
    document.querySelectorAll('.tools-block__title'),
    document.querySelectorAll('.tools-arrows'),
    document.querySelectorAll('.tools-footer'),
    document.querySelectorAll('.history-video__btn'),
    document.querySelectorAll('.talk-circle'),
    document.querySelectorAll('.select-language'),
    document.querySelectorAll('.select-btn'),
    document.querySelectorAll('.select-menu'),
    document.querySelectorAll('.options .option'),
    document.querySelectorAll('.calculator-list__item'),
    document.querySelectorAll('.calculator-list__check'),
    document.querySelectorAll('.answer-question'),
    document.querySelectorAll('.answer-number'),
    document.querySelectorAll('.popup'),
    document.querySelectorAll('.popup-header'),
    document.querySelectorAll('.header-mobile'),
  ],
  flexElement: [
    document.querySelector('.header'),
    document.querySelector('.header-nav'),
    document.querySelector('.header-login'),
    document.querySelector('.header-reg'),
    document.querySelector('.main-content'),
    document.querySelector('.become-main'),
    document.querySelector('.become-main__right'),
    document.querySelector('.direction-top'),
    document.querySelector('.direction-buttons'),
    document.querySelector('.authors'),
    document.querySelector('.community-list'),
    document.querySelector('.tools-top'),
    document.querySelector('.history-wrap'),
    document.querySelector('.create-footer'),
    document.querySelector('.talk-circles'),
    document.querySelector('.talk-circles'),
    document.querySelector('.calculator'),
    document.querySelector('.calculator-main'),
    document.querySelector('.calculator-main__currency'),
    document.querySelector('.calculator-main__wrap'),
    document.querySelector('.calculator-main__amount'),
    document.querySelector('.calculator-main__slider-values'),
    document.querySelector('.answer-top'),
    document.querySelector('.answer-main'),
    document.querySelector('.footer-wrap'),
    document.querySelector('.popup-header__switch'),
    document.querySelector('.leave-footer'),
    document.querySelector('.leave-check'),
    document.querySelector('.leave-checkmark'),
    document.querySelector('.advertising-container'),
    document.querySelector('.header-menu'),
  ]
}